name: Apply Service Mesh Pattern with Meshery
on:
  workflow_dispatch:
    inputs:
      provider_token:
        description: "Provider token to use"
        required: true
      platform:
        description: "Platform to deploy Meshery to"
        required: true
      pattern_url:
        description: "URL of the pattern to be deployed"
        required: false
      pattern_file:
        description: "Name of the pattern file relative to the .github folder"
        required: false

jobs:
  apply-pattern-file:
    name: Meshery Pattern Apply 
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kubernetes
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.23.2'
          kubernetes version: 'v1.22.2'
          driver: docker

      - name: Apply Pattern
        uses: layer5io/mesheryctl-service-mesh-patterns-action@master
        with:
          provider_token: ${{ github.event.inputs.provider_token }}
          platform: ${{ github.event.inputs.platform }}
          pattern_url: ${{ github.event.inputs.pattern_url }}
